# Generated by Django 5.1.5 on 2025-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_jugador_estadisticas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
